namespace Dbox.Activities;

public sealed record ActivityCreateInput(
    string? Type,
    string? Title,
    string? Description,
    string? Status,
    string? Source,
    string? Area,
    string? Result,
    string? Impact,
    string? Effort,
    string? Reference,
    string? Metadata,
    bool TypeProvided,
    bool TitleProvided,
    bool DescriptionProvided,
    bool StatusProvided,
    bool SourceProvided,
    bool AreaProvided,
    bool ResultProvided,
    bool ImpactProvided,
    bool EffortProvided,
    bool ReferenceProvided,
    bool MetadataProvided);
